version: '3.8'
services:
  bitsong:
    image: bzone/bitsong:v0.11.0
    hostname: bitsong
    build:
      context: .
      dockerfile: Dockerfile.bitsong
    volumes:
      - ./bitsong:/bitsong/.bitsongd/
      - ./scripts/bitsong/setup.sh:/bitsong/setup.sh
    entrypoint:
      - /bitsong/setup.sh
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
  osmosis:
    image: bzone/osmosis:v12.1.0
    hostname: osmosis
    build:
      context: .
      dockerfile: Dockerfile.osmosis
    volumes:
      - ./osmosis:/osmosis/.osmosisd/
      - ./scripts/osmosis/setup.sh:/osmosis/setup.sh
    entrypoint:
      - /osmosis/setup.sh
    ports:
      - 27657:26657
      - 1417:1317
      - 9190:9090
      - 9191:9091
  hermes:
    image: bzone/hermes:v0.15.0
    hostname: hermes
    build:
      context: .
      dockerfile: Dockerfile.hermes
    volumes:
      - ./hermes:/hermes/.hermes
      - ./scripts/hermes/config.toml:/hermes/.hermes/config.toml
      - ./scripts/hermes/key.bitsong.json:/tmp/key.bitsong.json
      - ./scripts/hermes/key.osmosis.json:/tmp/key.osmosis.json
      - ./scripts/hermes/setup.sh:/hermes/setup.sh
    entrypoint:
      - /hermes/setup.sh
    restart: always
    depends_on:
      - bitsong
      - osmosis
      
  explorer:
    build:
      context: ./tools
      dockerfile: Dockerfile.explorer
    volumes:
      - ./tools/explorer/chains/mainnet:/explorer/src/chains/mainnet
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: yarn serve --host 0.0.0.0 --disable-host-check
    depends_on:
      - bitsong
      - osmosis